# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install Python dependencies
RUN pip install --no-cache-dir httpx "mcp[cli]>=1.5.0"

# Copy project files
COPY . /app

# Default command to run the MCP server
CMD ["python", "paperpal.py"]
